README.md, help_section.py
Fixes #13.
Turns out `basicsr@1.4.2` fails to install for many Windows users because during its setup, `pytorch` (a sub dependency) fails to install. And `pytorch` fails because it can't find a certain file on disk (in this specific case, `learning_rate_adaption_op_test.test_learning_rate_adaption_op_normalization.zip`).
[Turns out](https://github.com/pytorch/pytorch/issues/23823#issuecomment-518410698) this is a known issue with `pytorch` and is actually caused by file paths being too long. Windows apparently maxes out around 260 characters, unless you specifically tell Windows to allow long paths.
You can do this by:
1. Open up the Window registry (Start > Run > `regedit`)
2. Navigate to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem`
3. Set `LongPathsEnabled` to `1` …
=> Document fix for Windows long file path error

__init__.py, classes.py, operators/dream_texture.py, ui/panel.py
This adds a readonly slider that replaces the generate button when in progress:
A 'Free Generator' operator has also been added to hopefully solve #42
=> Add simple progress indicator

operators/dream_texture.py, property_groups/dream_prompt.py, ui/panel.py
Replaced seed selection with a random seed bool and manual seed string properties. The string property will allow seeds to be anything within a 32-bit uint (which appears to be the limit from pytorch's internals pytorch_lighting/utilities/seed.py seed_everything()) and fixes #41.
If the seed cannot be parsed to an int it will get a seed based on its hash. After an image is generated the seed property will get updated with the random seed or hash so someone may easily disable random seed to tweak settings when a desired seed is found.
=> Improved seed selector

operators/dream_texture.py
I was getting this error in the System Console. This is a fix.
```
for region in context.area.regions:
AttributeError: 'NoneType' object has no attribute 'regions'
```
=> Fixed AttributeError with NoneType in context.area.regions

generator_process.py, operators/dream_texture.py, operators/open_latest_version.py, ui/panel.py
Adds some error handling while loading dependencies within the subprocess and directs users who appear to have downloaded source to instead download from releases.
=> Direct users who downloaded source to download release

generator_process.py, operators/dream_texture.py
This is run every time the `GeneratorProcess` is started, so you don't need to do more than one thing in the preferences window. I also did not use the `preload_models.py` script from InvokeAI for more control over how it works.
=> Add preload models step

__init__.py, preferences.py
Prevents a second installation of Dream Textures to be registered when one already is. Before it would cause some classes of the first installation to be unregistered, fail to fully register, and prevent the first installation from being able to be fully unregistered without a restart.
Also adds a warning when it appears to be installed from source zip in the preferences panel, previous "fix" #134 was insufficient as I forgot to account for the stable_diffusion directory not being included in source.
=> Fix some install issues

generator_process.py, operators/dream_texture.py
Redesigned backend to frontend IPC messages to be more easily modified and less prone to cause complicated issues like exceptions in the middle of writing an action to stdout. Added docstrings so other maintainers can better understand what a few parts do. Exception messages can now include a simplified user seen message and a stderr printed stacktrace, and has simplified integration when send_exception() is called within an except block. Message sending is also simplified by the send_action() function automatically packaging kwargs into json instead of individually writing things to stdout.
Fixes regression #192. The error check that is causing that regression has been swapped for a similar one that doesn't have expectations based on user input width and height.
=> Subprocess IPC improvements

operators/view_history.py, property_groups/dream_prompt.py, ui/panel.py
The sampler argument needed to be called `sampler_name`, this is why sampler choices were not being respected.
=> Fix sampler argument

generator_process.py
Due to the stable diffusion branch change cv2 now gets imported and doesn't play well with how Blender doesn't keep `python3.dll` in the same directory as `python.exe`. This fix allows the subprocess to be aware of its location.
=> Fix cv2 ImportError

README.md, __init__.py, absolute_path.py, classes.py, generator_process.py, operators/dream_texture.py, operators/upscale.py, property_groups/dream_prompt.py, requirements-mac-realesrgan.txt, requirements-win-torch-1-11-0.txt, ui/panel.py, weights/realesrgan/.gitignore
A new "AI Upscaling" panel has been added. I also refactored the generator process a bit to allow for multiple "Intents" (the two current ones being `PROMPT_TO_IMAGE` and `UPSCALE`)
=> Add Real-ESRGAN integration

__init__.py
Blender (at least on Windows) will only reload `__init__.py` when the user enables the addon and detects that the file has changed, leaving all other modules from the addon still loaded and leads to `__init__.py` attempting to use out-of-date modules after installing a new version.
This change will allow  `__init__.py` to clear those modules so they too get reloaded.
Installing a new version will still require that the previous version is disabled, removed from Blender, or when left enabled it is disabled and enabled again after installed.
Version is misleading. bl_info gets updated when the new version is installed. It was still running 0.0.6 at the start of the gif
=> Clear Modules from a Previous Install

classes.py, generator_process.py, operators/dream_texture.py, operators/upscale.py, ui/panels/dream_texture.py
- Cancel Generate operator allows for stopping without killing the subprocess and reloading everything next time
- Added `send_intent()` method to `GeneratorProcess` that mirrors what `send_action()` does
- Subprocess state is now managed by the `Backend` class to clean up `main()`
- Subprocess now uses a background thread for reading stdin so new intents can be processed while one is already running
- Intents are split into their own generator functions that allow for lazy loading their dependencies and models, won't have to wait on stable diffusion models if you're only starting the subprocess for upscaling
- Includes a fix for #265
=> More Subprocess Refactoring and Cancel Generate Operator

render_pass.py
Delete pointers into the shared memory buffer before closing the shared memory. Without this I got some errors when trying to close the buffer (on linux at least).
fixes #298
=> delete pointers before closing shared memory

generator_process.py
For some people the subprocess has managed to load external modules and cause odd issues. I've tracked down these ways that it may happen and should no longer be a problem with these changes.
1. PYTHONPATH environment variable: Becomes an issue when Blender is run with `--python-use-system-env` since the subprocess inherits Blender's environment variables. Now it'll always be removed from the subprocess's environment.
2. [User site](https://peps.python.org/pep-0370/): Blender will block use of the user site unless ran with `--python-use-system-env`, but the subprocess doesn't inherit this functionality. `-s` command line argument will prevent this.
3. Blender's site-packages: Some other addons may install their own packages there, and potentially packages installed from older versions of …
=> Import Fixes

__init__.py, generator_process.py, operators/upscale.py, ui/panels/upscaling.py
This adds an extra checkbox to upscaling that'll prevent artifacts around the edges of a seamless texture.
=> Upscale Seamless Fix

render_pass.py
Just found this bug moments after you merged. Most recent changes wasn't using the color transforms at all. Looks like inverting the color transform worked perfectly.
=> render pass set pixels fix

__init__.py, absolute_path.py, builtin_presets/Debug.py, builtin_presets/Final.py, builtin_presets/Preview.py, classes.py, generator_process/intents/prompt_to_image.py, preferences.py, property_groups/dream_prompt.py, ui/panels/dream_texture.py, ui/presets.py, weights/config.yml, weights/stable-diffusion-v1.4/.gitignore
This adds the ability to create and load presets for the 'Advanced' panel with the built-in Blender UI:
Three defaults are included:
* Preview - lower steps for prototyping
* Steps 25
* Show Steps: Off
* Final - higher steps for final generations
* Steps 50
* Show Steps: Off
* Debug - shows each step
* Steps 25
* Show Steps: On
> **Note** Model weights were moved to `weights/stable-diffusion-v1.4`, so they are no longer in `stable_diffusion/models/ldm/stable-diffusion-v1`
=> Advanced Presets

generator_process/__init__.py, generator_process/intents/prompt_to_image.py, requirements-lin-win-colab-CUDA.txt
Had an issue that's already been addressed upstream: [ModuleNotFoundError: No module named 'models.clipseg'](https://github.com/invoke-ai/InvokeAI/issues/1150), and ran into another issue with a different module causing the subprocess to hang when attempting to generate.
=> clipseg fix

__init__.py, generator_process/intents/prompt_to_image.py, operators/dream_texture.py, prompt_engineering.py, property_groups/dream_prompt.py, ui/panels/dream_texture.py
This adds a new prompt preset called "File Batch", which runs the prompts from each line of a file:
I also re-enabled the "Iterations" option, as it seems to be working fine now.
=> Add File Batch and Re-Enable Iterations

classes.py, operators/inpaint_area_brush.py
This replaces the manual stroke operator with a `GizmoGroup` that updates the "Draw" brush's blend mode when the "Mark Inpaint Area" brush is selected/de-selected.
Another hack, but this one seems to actually work well.
=> Fix InpaintAreaBrush behavior

__init__.py, absolute_path.py, classes.py, generator_process/__init__.py, generator_process/intents/prompt_to_image.py, operators/dream_texture.py, property_groups/dream_prompt.py, render_pass.py, requirements-lin-win-colab-CUDA.txt, requirements-mac-MPS-CPU.txt, ui/panels/dream_texture.py, weights/clipseg/.gitignore
* The init image panel was redesigned to better support multiple types of image manipulation:
* 'Replace' option for inpainting allows the masked area to be replaced by noise
* 'Prompt' mask source uses CLIP segmentation to create an inpainting mask from a text prompt
* Outpainting support added, with a simple stretch/blur fill used to provide backing color information. The 'Replace' option could also be used to simply fill the new area with noise.
> **Note** A new git dependency was added for `clipseg` in the latest InvokeAI changes.
=> Init Image Redesign and Outpainting

__init__.py, classes.py, preferences.py
Updates the "author" info to simply say "Dream Textures contributors" and links to the contributors section of GitHub for more information. I also cleaned up some unused operators and added more clarification around "Install Dependencies" (as some users still try to use this).
=> Add section linking to GH contributors

generator_process/intents/prompt_to_image.py
Looks like I had accidentally shadowed a variable when reorganizing with the Backend class, which is causing a crash when attempting to download certain models before generating.
Fixes #342
=> tqdm decorator fix

generator_process/block_in_use.py, operators/dream_texture.py, render_pass.py
A regression was introduced when color correction was added, causing the render pass to use it when it shouldn't be, and other odd bugs cascading such as the frontend during OCIO inversion receiving that color corrected image while its backend crashes attempting to open an already closed shared_memory object.
These changes make sure that the render pass does not use the prompt_to_image color correction and keeps later stages from running until the previous one is entirely completed to prevent race conditions.
=> Render Pass Fix

generator_process/__init__.py, generator_process/intents/prompt_to_image.py, operators/install_dependencies.py, preferences.py
Main included fix is for `SSLCertVerificationError` while importing `kornia`. Made it so the base `ssl` module can use `certifi`'s `cacert.pem` file. The Blender 3.3.1 version I used has a broken `ssl` module that points to certs which do not exist, and I doubt this is the only version with the same problem.
```python
>>> import ssl
>>> ssl.get_default_verify_paths()
DefaultVerifyPaths(
cafile=None,
capath=None,
openssl_cafile_env='SSL_CERT_FILE',
openssl_cafile='/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/ssl/cert.pem',
openssl_capath_env='SSL_CERT_DIR',
openssl_capath='/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/ssl/certs'
)
>>> import os
>>> import certifi
>>> os.environ['SSL_CERT_FILE'] = certifi.where()
>>> …
```
=> Linux Fixes

operators/view_history.py
When creating images, their are stored as a datablock with only the seed as name. Thus it would be very helpful to also have the seed in the history to make it easier going back to promt and fine-tuning.
=> Show the seed in history to easier match generated images to their promts

generator_process/actor.py
Unix based systems use the multiprocessing context `fork` whereas Windows and macOS systems use `spawn` by default. This is leading to the `_load_dependencies()` function never being called so most of the backend is non-functional.
Fixes #430
=> Always use spawn multiprocessing context

operators/project.py
This change makes texture projection no longer reuse the first UV map in an object. Instead, it will always use a map with the name "Projected UVs", and add a UV Map node to the node tree to refer to this map.
=> Stop reusing the first UV map slot for texture projection

operators/project.py, operators/project_helpers/draw_projected.py
Reset depth test mode after drawing specific maps, add some debug messages for clarity.
=> Reset depth test mode, debug messages

engine/__init__.py, engine/annotations/ade20k.py, engine/annotations/depth.py, engine/annotations/openpose.py, engine/annotations/viewport.py, engine/engine.py, engine/node_executor.py, engine/nodes/annotation_nodes.py, engine/nodes/pipeline_nodes.py, engine/nodes/utility_nodes.py
This adds built-in support for the segmentation ControlNet model. Apply labels to objects then use them in the render engine to produce segmentation maps that use the ADE20K classes/colors.
=> Add segmentation ControlNet support

generator_process/actions/control_net.py, operators/dream_texture.py
Fairly simple implementation. The inpainting-specific latents are created as-needed in the `control_net` action. Other inpainting mask logic is copied from the `inpaint` action.
=> Support Inpainting with ControlNet

__init__.py, generator_process/actions/control_net.py, generator_process/actions/depth_to_image.py, generator_process/actions/image_to_image.py, generator_process/actions/inpaint.py, generator_process/actions/prompt_to_image.py, operators/dream_texture.py, property_groups/dream_prompt.py, ui/panels/dream_texture.py
This adds a new optimization that limits the number of steps classifier-free guidance is performed on.
Using a `cfg_end` value of `0.5` reduced inference time by around 22% in my tests.
> As seen here: https://twitter.com/Birchlabs/status/1640033271512702977
<table>
<tr>
<th>1.0 (disabled)</th>
<th>0.5</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Add CFG End Optimization

requirements/linux-rocm.txt
Currently we will miss ROCm wheel and install Torch-CUDA with linux-rocm.txt line "torch>=1.13" so I bumped the --extra-index-url to the new ROCm and the version to 2.0
=> Bump Torch ROCm version to 2.0

engine/__init__.py
These files were not registered, but they were still present in the node categories. This commit follows the same hiding logic as in (un)registration.
This was my menu in 3.4, note the "Unknown" node
I since upgraded to 3.5, but I wanted to fix this for other 3.4 users!
=> Hide NodeResizeImage and NodeImageFile if not v3.5

engine/__init__.py, engine/engine.py, engine/node_executor.py, engine/nodes/input_nodes.py, engine/nodes/pipeline_nodes.py, engine/nodes/utility_nodes.py
This adds some nodes that are useful for things like feedback loops and image manipulation.
New nodes:
* Image File - opens an image from a file path (Blender 3.5+ due to OpenImageIO availability)
* Frame Path - Gets the path to a frame at a specific index
* Crop Image - Crops an image with a bounding rect
* Join Images - Stacks two images horizontally or vertically
* Separate Color - Splits image into RGBA channels
* Combine Color - Creates image from RGBA channels
* Switch - If statement
* Compare - `>`, `<`, `==`, etc.
* Replace String - Find and replace in string
=> Add more nodes

operators/dream_texture.py, operators/upscale.py, ui/panels/dream_texture.py, ui/panels/upscaling.py
- When there are multiple image editors, generating from an open image source or upscaling will now pick the image from the image editor it was executed from.
- Image editors with image pin activated will no longer be replaced with generated images.
- Cancel generator operator has been slightly changed to better differentiate it from release generator.
- Image texture nodes will now fill the shader editor view better instead of just the bottom right corner.
=> Various UI Tweaks

generator_process/actions/choose_device.py, generator_process/directml_patches.py, generator_process/models/optimizations.py
Allows DML execution in submodules to retry running when it runs out of memory. Sometimes this can allow generation to finish, but often it'll occur again on a later step and not recover from it.
Found and fixed some DML issues caused from merging the last branch.
It can run SDXL, but may require offloading depending on what GPU is used. Using half VAE tiling is also effective and maintains good decoded image accuracy.
=> DirectML Out of Memory Retry

generator_process/actions/prompt_to_image.py
`load_model` only returns a tuple when `sdxl_refiner_model` is not `None`.
Issue described in more detail here: https://github.com/carson-katri/dream-textures/pull/711#issuecomment-1774135168
=> Check for refiner before unpacking tuple from `load_model`

operators/project.py, property_groups/dream_prompt.py
This resolves the following issues with texture projection:
1. Incorrect error reporting -- updated to use the revised `FixItError` type
2. ControlNet being ignored when no image associated. This conditional check was incorrect, as `control_images` are now passed in as a separate argument.
=> Fix depth projection with ControlNet

generator_process/actions/load_model.py
This is a workaround for the following issue in diffusers: https://github.com/huggingface/diffusers/issues/5593
=> ControlNet `AutoPipeline.from_pipe` lookup workaround

generator_process/actions/prompt_to_image.py
Some [changes to `LoRACompatibleConv`](https://github.com/huggingface/diffusers/blame/2b23ec82e898aa1f0e172da6ef054631634b643d/src/diffusers/models/lora.py#L232) in diffusers broke seamless generation. This patches `LoRACompatibleConv.forward` to avoid using the functional `conv2d` (which will ignore the padding mode) and instead use our custom `_conv_forward_asymmetric`.
=> Support seamless for latest diffusers

generator_process/future.py, preferences.py, ui/panels/dream_texture.py
=> Fix Generating from Opened Blend File

operators/project.py
When the language is set to something other than English, or the "Principled BSDF" node is renamed, the subscript would fail.
The `type` property is a more accurate way of finding this node.
=> Locate Principled BSDF by type not name

requirements/linux-rocm.txt
Puts ROCm on 5.6 and Torch on 2.1
=> Bump versions linux-rocm.txt

.github/workflows/package-release.yml, .gitignore, generator_process/actor.py, scripts/zip_dependencies.py
Currently Windows users struggle to install packaged releases due to errors caused by long paths, even when long paths are enabled for their system. Once installed a certain file has an entire path length of 259 characters when not including the Windows username. This became more of a noticeable issue in the last release due to a path in the transformers module growing by 11 characters.
To help prevent this issue, this PR zips the transformers module separately and enables it to be loaded like normal. Now the max path length is 225, so installing shouldn't be an issue as long as the username isn't more than 34 characters or another module grows in path length. This method is a little limiting as it only supports zipping modules that use .py files, no .dll or other special files. The new …
=> Zip Dependencies with Long Paths

.github/workflows/package-release.yml, classes.py, diffusers_backend.py, generator_process/__init__.py, generator_process/actions/control_net.py, generator_process/actions/controlnet_aux.py, generator_process/actions/convert_original_stable_diffusion_to_diffusers.py, generator_process/actions/depth_to_image.py, generator_process/actions/huggingface_hub.py, generator_process/actions/image_to_image.py, generator_process/actions/inpaint.py, generator_process/actions/load_model.py, generator_process/actions/prompt_to_image.py, operators/dream_texture.py, property_groups/control_net.py, property_groups/dream_prompt.py, requirements/dreamstudio.txt, requirements/linux-rocm.txt, requirements/mac-mps-cpu.txt, requirements/win-dml.txt, requirements/win-linux-cuda.txt, ui/panels/dream_texture.py
1. Updated progress indicator to use the new `UILayout.progress` API. This is more semantically correct than using an `IntProperty`. Visually it looks nearly identical.
https://github.com/carson-katri/dream-textures/assets/13581484/da1e4e69-34cf-4fbd-ab14-9cedacb47d2e
2. Change "CFG Scale" min to `0`. This allows CFG to be disabled for models like `sdxl-turbo`.
3. New ControlNet UI based on Blender's updated modifier panel. I chose to use `box()` instead of registering/unregistering sub-panels for each row for simplicity. As far as I can tell, there is no way to get a stacked layout like this to work well in a UIList.
https://github.com/carson-katri/dream-textures/assets/13581484/3af15d4a-129d-4c38-8bd3-4e9c986d1b84
=> ControlNet processors and Blender 4.x UI tweaks

engine/engine.py
Bugfix: When creating the default node setup, use socket_type as keyword argument.
=> Small fix for default node setup

generator_process/actor.py
The recent PyTorch 2.3.0 version has a new MKL dependency on Windows that isn't being loaded due to the uncommon method of installing to a target directory.
Fixes `OSError: [WinError 126] The specified module could not be found. Error loading "...\dream_textures\.python_dependencies\torch\lib\shm.dll" or one of its dependencies.`
=> shm.dll fix

.github/workflows/stale.yml
This option should only run the stale bot on issues with the `bug` label. If any other labels are present, it will not mark the issue as stale.
The `confirmed` label, or a specifier label such as `AMD`, `NVIDIA`, `render pass`, can be used to disable the stale bot for an issue.
=> Only check for issues with 'bug' label

image_utils.py
This was failing before, as `foreach_set` is expecting a flat array instead of a 2D array of `(width * height, channels)`
=> Fix render pass image util to flatten array

generator_process/actions/huggingface_hub.py
Diffusers no longer provides a default variant.
This adds a check to see if the proper variant files are available before attempting to download them.
=> Don't pass variant if files are unavailable

.github/workflows/package-release.yml, __init__.py, engine/engine.py, generator_process/actions/depth_to_image.py, generator_process/actions/huggingface_hub.py, generator_process/actor.py, generator_process/directml_patches.py, image_utils.py, requirements/linux-rocm.txt, version.py
This will includes builds for Python 3.11, which are compatible with Blender 4.1+.
=> Release v0.4.0

image_utils.py, render_pass.py
Made a similar change in `image_utils.render_pass_to_np()` that was previously added to `image_utils.np_to_render_pass()` due to a change in Blender 4.1 no longer expecting a channel dimension when reading/writing to a render pass.
=> Fix Blender 4.1 Render Pass

generator_process/actions/huggingface_hub.py
Hello 👋
This PR updates some attributes and methods that are now deprecated in the `huggingface_hub` library.
- `modelId` is getting deprecated https://github.com/huggingface/huggingface_hub/issues/2408
- `ModelFilter` has been deprecated for some time (see https://github.com/huggingface/huggingface_hub/issues/2028)
This PR will make the codebase more future-proof while being compatible with existing versions of `huggingface_hub`. Let me know if you have any questions :hugs:
=> Update Hugging Face utilities

.github/ISSUE_TEMPLATE/bug_report.yml, requirements/linux-rocm.txt
=> Remove `nightly` prefix from ROCm `extra-index-url`
